const questions = [
  {
    _key: "DA9dG4E6ko8rY_mlW_phX",
    text: "Hvilken elv renner under fjellet Mannen?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "kGYCTIREL14f2jXdqqa3I", text: "Rauma", correct: !0 },
      { _key: "dFjM87yLV0ruZB89j0q6A", text: "Gaula", correct: !1 },
      { _key: "LdR9VIftDmDxoUPl1t6QT", text: "Glomma", correct: !1 },
    ],
  },
  {
    _key: "o4au2ZDQ_cxuezP1_xZu5",
    text: "Misjonæren som grunnla byen kalte den Godthåb. Hva heter byen nå?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "wP5JqWSXQCMSyRPT6JIXA", text: "Nuuk", correct: !0 },
      { _key: "evjLrUtfYJAXZkzDoFMcK", text: "Qaqortoq", correct: !1 },
      { _key: "hcAXj-uaoaZfgevWPF5hX", text: "Qaanaaq", correct: !1 },
    ],
  },
  {
    _key: "ShfbwdTauUMA71FyCWg1Z",
    text: "Quasimodo med pukkelen forelsket seg i Esmeralda her",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "j_OdGaJHmUwtQuYNV7nOI", text: "Paris", correct: !0 },
      { _key: "3JM_C6IbySYPdF6kHOpzG", text: "Lyon", correct: !1 },
      { _key: "rD58NhxrHJAijFxhGxKU5", text: "Marseille", correct: !1 },
    ],
  },
  {
    _key: "sMtYrKMtPDLRg4b7yQedt",
    text: "Spanias kong Filip 2. ga navn til en øystat i Stillehavet. Hvilken?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "-WJEyW9aMPahhH9y35F0v", text: "Filippinene", correct: !0 },
      { _key: "Z6MZUnvQKRLdDi_GJWhQL", text: "Brunei", correct: !1 },
      { _key: "1fbB0qhpjXdpAQtPvm0Z6", text: "Maldivene", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "kgLp2hDmLC0ipyM9Q1MpK", text: "Oslo", correct: !0 },
      { _key: "UIff0qac5t1x7NNM6lwqJ", text: "Moss", correct: !1 },
      { _key: "yrhbQ0SEg3mSL284RLgyz", text: "Fredrikstad", correct: !1 },
    ],
    _key: "fZKl2wihRH7rFktUmaKJT",
    text: "Hvor kommer rapgruppa Undergrunn fra?",
    difficulty: "easy",
    category: null,
  },
  {
    _key: "Q5-qNpQHRzx41K4O9W-vD",
    text: "Else Kåss Furuset skal gifte seg 20. april. Hvor skal det skje?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "fONgJyiLHzwITGWltCFLf", text: "Oslo Spektrum", correct: !0 },
      { _key: "MOleC19lsJ7ZWnNe1yGT4", text: "Oslo Domkirke", correct: !1 },
      { _key: "d2HdW_5zMnz0W2PuvzX81", text: "Oslo Rådhus", correct: !1 },
    ],
  },
  {
    _key: "3-kiILnO50jtvXDWmDDvM",
    text: "Reis til stedet Marcus & Martinus vokste opp",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "g4tcWz4X1R6nbStjuWBCt", text: "Trofors", correct: !0 },
      { _key: "sQZdzF7jvDQh5Lo2G7Boi", text: "Mosjøen", correct: !1 },
      { _key: "BJuxDGV6fSTaagrFvc8Bw", text: "Selfors", correct: !1 },
    ],
  },
  {
    _key: "Q7SZNcXFgXU0asf99UETv",
    text: "Hopp opp på rullebrettet og spark deg dit sporten startet",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "6rItvlRCPjfG_iA1cP6jI", text: "California", correct: !0 },
      { _key: "LgoYThKKgehWCGvzhrZuT", text: "Manchester", correct: !1 },
      { _key: "fHJHPhANXYQhvGe722pIt", text: "Barcelona", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "tk2ImCRYt5hx9SKTbOwQi", text: "Malmö", correct: !0 },
      { _key: "660VgsU6dq6ZDqsvNkiug", text: "Liverpool", correct: !1 },
      { _key: "SZyPaA72GGw7MKf-CBbLk", text: "Torino", correct: !1 },
    ],
    _key: "GYOBLBmjrMUfMmEeQ60ms",
    text: "Hvor skal årets finale i Eurovision Song Contest være?",
    difficulty: "easy",
    category: null,
  },
  {
    category: null,
    answers: [
      { _key: "2nDYvqYYDHFCdSBHKlRyy", text: "Lærdal", correct: !0 },
      { _key: "ZtiGbpV-cwUqNJOW65Fn9", text: "Tromsø", correct: !1 },
      { _key: "toc2jnzjnnUEb9sjLJy1g", text: "Ålesund", correct: !1 },
    ],
    _key: "j_29wJpTFsVwmVGm0qGmN",
    text: "En brann skadet 60 bygninger i en norsk bygd for ti år siden. Hvor?",
    difficulty: "easy",
  },
  {
    _key: "E-Q_sGj1mVIhBsD8KuPiO",
    text: "Hvor er visesangeren som er kjent for «Barn av regnbuen» fra?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "lmSMwDVwbFQaxwfy5whq9", text: "Oslo", correct: !0 },
      { _key: "DIQCtu1Dm_Wx8BgPxnowW", text: "Porsgrunn", correct: !1 },
      { _key: "zzwvbjWT1iQ1ncV1FoTcf", text: "Notodden", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "-pTu2T_YvcMAG3sZ3sYBN", text: "Rødehavet", correct: !0 },
      { _key: "WyHKts1wfFtFBpigYkrh_", text: "Stillehavet", correct: !1 },
      { _key: "swkBA6fBWSA6gc1oNeDVV", text: "Atlanterhavet", correct: !1 },
    ],
    _key: "pqCKo5BSUJ3IFqM_sndJi",
    text: "Reis med båt gjennom Suezkanalen fra Middelhavet. Hvilket hav kommer du til?",
    difficulty: "easy",
    category: null,
  },
  {
    _key: "rE-01L6GSlE4nM5DqJokZ",
    text: "Moskeen Hagia Sofia har vært både kirke og museum. I hvilken by?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "vluGZM6Hvh4ygrqlMqdo9", text: "Istanbul", correct: !0 },
      { _key: "tJe56VWsqHkZypwPxxfXp", text: "Jerusalem", correct: !1 },
      { _key: "UMEcQaPZgJAw2lLwFb_JJ", text: "Damaskus", correct: !1 },
    ],
  },
  {
    _key: "vAEx9codaHkODPBwjAmM6",
    text: "Hvor skal Åge Aleksandersen ha sine avslutningskonserter?",
    difficulty: "easy",
    category: null,
    answers: [
      {
        _key: "enfQnxvpkncOmThkntPfp",
        text: "Lerkendal stadion",
        correct: !0,
      },
      { _key: "K3-EXLhBuXoPNS1OGuYN9", text: "Oslo Spektrum", correct: !1 },
      { _key: "epRT-lDOmIMoFmc8AORJ_", text: "Nidarosdomen", correct: !1 },
    ],
  },
  {
    _key: "eRQP653adycrd2-dxQiKW",
    text: "Silicon Valley er kjent for sine teknologiselskaper. Hvor ligger denne dalen?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "U5Hng4CLUTZ66pMVF_HA8", text: "San Francisco", correct: !0 },
      { _key: "Mw48sCi6W4QDu9DoP8cOm", text: "Texas", correct: !1 },
      { _key: "fy0tMzAZiv_CfXZMBuQ8N", text: "New Hampshire", correct: !1 },
    ],
  },
  {
    _key: "CzzAbJFQze7szpnoS3b8i",
    text: "Hvor startet protestbevegelsen «De gule vestene»?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "eSDDwBCnYxwls7vtpV6mp", text: "Frankrike", correct: !0 },
      { _key: "20vumTUDP0rEErPMTGjmZ", text: "Spania", correct: !1 },
      { _key: "r_DHI2RATqCpPt5pKrmIW", text: "Hellas", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "MS8_DIfhOZfu-wAaXXgqS", text: "Danmark", correct: !0 },
      { _key: "eWEQ0mkhiq1w9o4HGq6SY", text: "Storbritannia", correct: !1 },
      { _key: "dkHzSojFjuC8ZSsarCLdl", text: "Luxembourg", correct: !1 },
    ],
    _key: "o27hdBidMCuPQBsYfzDZz",
    text: "Hvor er Fredrik X konge?",
    difficulty: "easy",
  },
  {
    _key: "i37XaR6xNW1OX42st_hEN",
    text: "Reis til det nedlagte kjernekraftverket Tsjernobyl i dette landet",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "TidhKZNLUm_Kaq2Fiv4zF", text: "Ukraina", correct: !0 },
      { _key: "_nYGdM0TxQDLYZwxwpIXq", text: "Russland", correct: !1 },
      { _key: "WglL-XbDmuU04Hit9_L6Z", text: "Belarus", correct: !1 },
    ],
  },
  {
    text: "Ta med flagget og besøk byen hvor årets Sommer-OL arrangeres",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "bFKdP6adi95r1Xs-3wqez", text: "Paris", correct: !0 },
      { _key: "Nklf-YfdkhJlQFX_73y1u", text: "Kairo", correct: !1 },
      { _key: "NHRIKTp-rbTgNi2-8lVCi", text: "Moskva", correct: !1 },
    ],
    _key: "lhci_SuEulOBcTZwco_TG",
  },
  {
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "h7VSyKT4MkRPYwVL2Sa2P", text: "Stillehavet", correct: !0 },
      { _key: "UWuMuwMq48JpxzE7mB8jD", text: "Egeerhavet", correct: !1 },
      { _key: "HygS-UU1QxcAReTEBa7Db", text: "Adriaterhavet", correct: !1 },
    ],
    _key: "8WYmHUCKfd_Z2JLTSNsoh",
    text: "Hvilket hav er det Panamakanalen forbinder Atlanterhavet med?",
  },
  {
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "wGwJeaMKUqQgGKG657S3S", text: "St. Petersburg", correct: !0 },
      { _key: "BJLsueumX_vgztF75QHZt", text: "Moskva", correct: !1 },
      { _key: "D16gVy5ReUiBhWpSHIGt4", text: "Leninogorsk", correct: !1 },
    ],
    _key: "xcgqlFNSSelUywGx5isHv",
    text: "Byen het Leningrad tidligere. Hva heter den nå?",
  },
  {
    _key: "FpTNRowrcfasjyLGpWlgO",
    text: "Ta på deg badetøy og ta en dukkert i Den blå lagune. Hvor?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "5Cn-3WQyu5L6ee02_mX_-", text: "Island", correct: !0 },
      { _key: "ojn2vpNNHC93s6yGGRlku", text: "Filippinene", correct: !1 },
      { _key: "SLn9CxvzkhXalwsJTCjP9", text: "Maldivene", correct: !1 },
    ],
  },
  {
    _key: "-iGOSQvftgdG55spRLnMx",
    text: "Ta med deg paraply til stedet som har norsk rekord i nedbør per døgn",
    difficulty: "easy",
    category: null,
    answers: [
      {
        _key: "pgG0xB-FJPzzlJQo1xrSX",
        text: "Indre Matre i Vestland",
        correct: !0,
      },
      {
        _key: "cbUgWXVDSXSPQfCw4h5Nl",
        text: "Vatne i Rogaland",
        correct: !1,
      },
      {
        _key: "EPBy_nPmYFJI_M5HOmLj0",
        text: "Vennesla i Agder",
        correct: !1,
      },
    ],
  },
  {
    answers: [
      { _key: "FykXliwBkbbBlMQXBqZSg", text: "Elverum", correct: !0 },
      { _key: "9bjmpuk9dTG_Gd4TxXYMA", text: "Dombås", correct: !1 },
      { _key: "AVhxFRlcuC34fN8L-c64b", text: "Ringebu", correct: !1 },
    ],
    _key: "J6CQHBpv4wttyhHzIZifk",
    text: "Reis til stedet ved Glomma som har oppkalt en gate etter Ole Paus",
    difficulty: "easy",
    category: null,
  },
  {
    _key: "niV3-yzj-vp6rq-U7oxkq",
    text: "Spis paella i landet som har det som nasjonalrett",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "y5OAjIMem66tESq-uqj2p", text: "Spania", correct: !0 },
      { _key: "yjhGEBlC6NYMQYlukszRt", text: "Puerto Rico", correct: !1 },
      { _key: "pwtithEBgW9wysapgaxZ9", text: "Cuba", correct: !1 },
    ],
  },
  {
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "Oxd7PO1PRHiWfLJ25I01d", text: "Atlanterhavet", correct: !0 },
      { _key: "MWq1El27FTuxcRMdco4NJ", text: "Stillehavet", correct: !1 },
      { _key: "euZ9glZpGmlFa2IfCMz_F", text: "Indiahavet", correct: !1 },
    ],
    _key: "v3RZoPCaiM1bRZGLS5Xcn",
    text: "I hvilket hav ligger Færøyene, Azorene og Madeira?",
  },
  {
    _key: "1jG91byEBPQBkEXFVnlyQ",
    text: "Hvor begynte de å lage tekstiler av silke?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "RS1hrchZp52UzAGdjWP26", text: "Kina", correct: !0 },
      { _key: "_Uw2Sqc1ykcKDCZEfzmu5", text: "Thailand", correct: !1 },
      { _key: "3zXan6BWQ_TlrZ6QmLpPd", text: "Russland", correct: !1 },
    ],
  },
  {
    _key: "v79Q3oRwr9U1f-KQ96ho9",
    text: "Reis til byen der sjøforsvarets hovedbase Haakonsvern ligger",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "hwvn8cuX8RqImtubxaHCI", text: "Bergen", correct: !0 },
      { _key: "mqEqThRCPujulJIP7v6a-", text: "Andøya", correct: !1 },
      { _key: "w19_NKnIlFzUH4iQ9fFOv", text: "Ørland", correct: !1 },
    ],
  },
  {
    _key: "ZcTUjn9iDZF87x57D15MT",
    text: "Besøk museet Troldhaugen. Hvor drar du?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "AD4l8YVtktInCtiyroHOu", text: "Bergen", correct: !0 },
      { _key: "arnB7kfTrdMVNDOTf8e_3", text: "Lillehammer", correct: !1 },
      { _key: "3KVWQ_-E70mD0co-8aVWa", text: "Stavanger", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "w7lAf8hEx0CKVJsuTCqIR", text: "Jamaica", correct: !0 },
      { _key: "xaZkEWkD5PSYWN4tzkWlW", text: "Sør-Afrika", correct: !1 },
      { _key: "JwIptH6cmoO6BgboeLhL2", text: "Storbritannia", correct: !1 },
    ],
    _key: "wMB5au_GHvEryaSfykhMv",
    text: "Slå ut håret i reggaemusikkens hjemland",
    difficulty: "easy",
  },
  {
    _key: "bhZOYONHUm_iyGCGRv1JJ",
    text: "I hvilket land lever Barbie i filmen «Barbie»?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "_LpCY_pP4nAlkzMMmFsTj", text: "Barbieland", correct: !0 },
      { _key: "zGuqB8iuudC2w7cIbHq50", text: "USA", correct: !1 },
      { _key: "D0HOiSvce5RhTHnHe_AHn", text: "Canada", correct: !1 },
    ],
  },
  {
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "neMDqVDNqBvXMaMp2o-M8", text: "Sverige", correct: !0 },
      { _key: "IE5ZFjoDiDk31C7jvro2x", text: "Storbritannia", correct: !1 },
      { _key: "910-pzSz942JgongzUSUs", text: "Belgia", correct: !1 },
    ],
    _key: "vCi7cHsubvGBX9kDXrDKM",
    text: "Hvor foregår handlinga i «Young Royals»?",
  },
  {
    _key: "xvy9gXpigdGdcFNGMVkyy",
    text: "I hvilket av disse landene kan du bli syk av malariamygg?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "atv7YjpcyOEDCadWDd4Sg", text: "Sudan", correct: !0 },
      { _key: "VUEX04AmRX91MQSXSGsYm", text: "Norge", correct: !1 },
      { _key: "XSMOyGNNT4oJFj7hby_gH", text: "Sverige", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "3xWQuOHPus7Vl-ASyc5Jo", text: "Stranda", correct: !0 },
      { _key: "Ku4LXFWnPoaYZdN9S7LCC", text: "Sauda", correct: !1 },
      { _key: "gkFlYciq1UAx7zLzIt2bs", text: "Sortland", correct: !1 },
    ],
    _key: "mkEHYlIv3ZH5PX1mrnJu3",
    text: "Hvor blir pizzaen Grandiosa produsert?",
    difficulty: "easy",
    category: null,
  },
  {
    category: null,
    answers: [
      { _key: "emAgOZy0Dppt9Gl4PUauo", text: "Bergen", correct: !0 },
      { _key: "6aRKtSfySWs0wAjC6ekyh", text: "Oslo", correct: !1 },
      { _key: "WMyjfiDgk-NGxLsY__4sa", text: "Tromsø", correct: !1 },
    ],
    _key: "1Z4_edVM2ORebspTl9rpB",
    text: "Hvor kan du se teater på Den Nationale Scene?",
    difficulty: "easy",
  },
  {
    _key: "flb1N8Os1iQc-tbHabIuh",
    text: "Reis til landet hvor youtuber Mr. Beast kommer fra",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "7ePXtc08R8AwExIlYUgER", text: "USA", correct: !0 },
      { _key: "IecuLZ-LnA1tWwRkqFF77", text: "Storbritannia", correct: !1 },
      { _key: "gBj0JloQ88KgxUIHF2-KY", text: "Australia", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "4tqnWkdIdDI5R1e2wmbyL", text: "Oslo", correct: !0 },
      { _key: "OXOb3K8GTJnx-5324ZSoa", text: "Bergen", correct: !1 },
      { _key: "c50VQa_I0NR0DPGv5j02-", text: "Kristiansand", correct: !1 },
    ],
    _key: "6Slmvd5RKRxOkXEqK-JN5",
    text: "Hvor finner du Thorbjørn Egners plass?",
    difficulty: "easy",
  },
  {
    _key: "_catGlQzK-YuacgSPq0AN",
    text: "Breakdance er en ny øvelse i OL. Hvor oppsto sporten?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "3lzGEck9-X4V9eHcU1kiS", text: "New York", correct: !0 },
      { _key: "2Rtj4EA34YG3jpKyp0JnM", text: "Las Vegas", correct: !1 },
      { _key: "pccDIOfwlTO77LH21eOgn", text: "Sydney", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "DfbCk8hcqY6T-MpKVdY63", text: "Sicilia", correct: !0 },
      { _key: "qpAlq1Vn2o_FT2kH38Dch", text: "Kypros", correct: !1 },
      { _key: "Jo_Hg3EHKC-pr4ddaJa0C", text: "Mallorca", correct: !1 },
    ],
    _key: "XsTI0ZU92SZm74Kdhfay7",
    text: "Hva er Middelhavets største øy?",
    difficulty: "easy",
    category: null,
  },
  {
    _key: "Adf0YzpXsFeA6MHAB7HOg",
    text: "Hvor er Abu Dhabi hovedstad?",
    difficulty: "easy",
    category: null,
    answers: [
      {
        _key: "WttDBczM5OAUg-wtl5lA7",
        text: "De forente arabiske emirater",
        correct: !0,
      },
      { _key: "iAx3RKqMX33qvmcLdgkMq", text: "Oman", correct: !1 },
      { _key: "LOWiFKek7VEuWB7Tg9Dz2", text: "Qatar", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "ZIJL1LZstSrrX0y--_BYY", text: "Japan", correct: !0 },
      { _key: "At0KOMrdu1poASFUDxLQE", text: "Turkmenistan", correct: !1 },
      { _key: "bJEDXWTVNGigWhbjRHwjA", text: "Polen", correct: !1 },
    ],
    _key: "ey7SQdALYGlAyGSjXB6mw",
    text: "Ta på deg det svarte beltet og dra dit judo ble oppfunnet",
    difficulty: "easy",
  },
  {
    answers: [
      { _key: "MaHPwKdbYzqq1Skwj7KcB", text: "Lønneberget", correct: !0 },
      { _key: "_wof7PW2LLD4wYdRm0Yyv", text: "Gøteborg", correct: !1 },
      { _key: "M7sNgjxhjwmLG8EyBx3CE", text: "Åre", correct: !1 },
    ],
    _key: "5PbgK8es_ZW6xbfbTKpAy",
    text: "Hvor kommer Astrid Lindgrens figur Emil fra?",
    difficulty: "easy",
    category: null,
  },
  {
    _key: "pB1ALMJOlEFR4e1HOZ7Ip",
    text: "Hvilken by ble kalt Bjørgvin tidligere?",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "SNC6rL-oeEpz1exVpebSI", text: "Bergen", correct: !0 },
      { _key: "VWi70BP4qg6T_oUKtDWte", text: "Bodø", correct: !1 },
      { _key: "g6eAkKCQWLG75mu-dweqI", text: "Brønnøysund", correct: !1 },
    ],
  },
  {
    _key: "63XVlCI2bHC7fTTcWNKAh",
    text: "Sett deg i båten og ro til verdens største øy",
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "nrn-ugtg_3qRoftyHJEhC", text: "Grønland", correct: !0 },
      { _key: "kcH6PD10Noec_zcY-R8g0", text: "Madagaskar", correct: !1 },
      { _key: "84XesrJ0C35q1sFup7sZB", text: "New Zealand", correct: !1 },
    ],
  },
  {
    difficulty: "easy",
    category: null,
    answers: [
      { _key: "VRVQa1PaF2fqtLWE_FxIb", text: "Kina", correct: !0 },
      { _key: "6uUw0mU1Na08CRO679Oyn", text: "Japan", correct: !1 },
      { _key: "NEdt-w5p8dg6RieBZT3UK", text: "Singapore", correct: !1 },
    ],
    _key: "4O4AJGxTd9YAdN_3lPRa7",
    text: "Reis avgårde til landet som står bak TikTok",
  },
  {
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "dHiwLylSrTfCLK6iWGEyO", text: "Utvær", correct: !0 },
      { _key: "NZLdzbnpovYh3GZXnjbMU", text: "Ytterøyene", correct: !1 },
      { _key: "kTb29N_gyLbHFO6Lcjn7l", text: "Flåvær", correct: !1 },
    ],
    _key: "AMKR4meYfjQyy2iBLfGFJ",
    text: "Reis til den vestligste øygruppa av disse",
  },
  {
    category: null,
    answers: [
      { _key: "qlAb5Kz8fDUcVTJ3YvCFa", text: "Nikosia", correct: !0 },
      { _key: "4eVp4d988G3V4UvLJRrZz", text: "Athen", correct: !1 },
      { _key: "d29iL1F61CjGOZSPowqV0", text: "Pireus", correct: !1 },
    ],
    _key: "4zbgzGAETSbRv14GakvRo",
    text: "Reis til byen fotballklubben Apoel FC hører til",
    difficulty: "medium",
  },
  {
    _key: "k5afTUE7WMSOdHV5FjJcg",
    text: "Reis til Norges lengste og dypeste undersjøiske veitunnel",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "2x-VCC6owX1KangvNGITv", text: "Ryfylketunnelen", correct: !0 },
      {
        _key: "c99QZ7xVWuD_hRgtiEYWH",
        text: "Eikesundtunnelen",
        correct: !1,
      },
      {
        _key: "XsYXofFgY0VMRpDu2l4ro",
        text: "Oslofjordtunnelen",
        correct: !1,
      },
    ],
  },
  {
    text: "Hvor er Nr. 91 Stomperud fra?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "ZcnLZttm_gzHeJSjP2_X5", text: "Sørumsand", correct: !0 },
      { _key: "vzNTA8N3A9AwPrpqBEMcQ", text: "Rånåsfoss", correct: !1 },
      { _key: "fnSzVRLN9PVAYxvhObt4R", text: "Guttersrud", correct: !1 },
    ],
    _key: "9EgcXcKkOYo0pdYP4GbyY",
  },
  {
    _key: "q6-RT0WM-uxoqB5Tol27e",
    text: "Hva er hovedstaden i Mosambik?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "awsx6m_sT4Bk0GKMXekmt", text: "Maputo", correct: !0 },
      { _key: "hAtuqccJ1b4G-GAhYW1Mu", text: "Beira", correct: !1 },
      { _key: "Lq6WkIF82UZIQOTl-7PVG", text: "Pemba", correct: !1 },
    ],
  },
  {
    text: "I hvilken bydel bor Kjell i Olsenbanden?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "Z4Lr7gPUwTgY3YKygI1RB", text: "Kampen", correct: !0 },
      { _key: "-xs9xiIozZ1QR3cn2PdeU", text: "Sagene", correct: !1 },
      { _key: "QT2iayz_9OryCqaDl65Vq", text: "St. Hanshaugen", correct: !1 },
    ],
    _key: "Hfsm-D-DYfhRnl-5XE9hb",
  },
  {
    text: "Verdens første skipstunnel skal gå gjennom denne halvøya",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "WW5eJyMZVyhhIpHlcfwHF", text: "Stad", correct: !0 },
      { _key: "vquF4PlLCFEkjxp_blPsF", text: "Tingvoll", correct: !1 },
      { _key: "CXp72_68R9bXczRf2MvTU", text: "Sveio", correct: !1 },
    ],
    _key: "GC7Z9ObVr_olmbuHc-GjR",
  },
  {
    _key: "eo6tKu8SajtPA9yi_IEjZ",
    text: "Hva heter det farlige havstykket mellom Molde og Kristiansund?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "GL-v074rwUDymzbh_kQIU", text: "Hustadvika", correct: !0 },
      { _key: "ubA_Hhukr4PO_IhPS5fTq", text: "Stadthavet", correct: !1 },
      { _key: "gTAl8ebOI_jw35G9ZLi0U", text: "Kjuttaviga", correct: !1 },
    ],
  },
  {
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "jyblfNpmA5oKW-_VU4fj0", text: "Sagene", correct: !0 },
      { _key: "UbDSvx_rlC0PbCLbDLCZU", text: "Tøyen", correct: !1 },
      { _key: "owGKyICmGbB_KXUsaCAl0", text: "St. Hanshaugen", correct: !1 },
    ],
    _key: "MNKR0TUPncFFRGt6gU1l6",
    text: "Hva heter industristrøket som oppstod fra 1500-tallet langs Akerselva?",
  },
  {
    category: null,
    answers: [
      { _key: "ecMZjKXVZPaYjwTBEHUzM", text: "Frysja", correct: !0 },
      { _key: "ouzxsrJSdTFmvDSo4bFlB", text: "Maridalselva", correct: !1 },
      { _key: "_ZbSNKNO0fFHOUv7BvhBA", text: "Hoffselva", correct: !1 },
    ],
    _key: "97pqvpYnS-GUigbeuP57Q",
    text: "Akerselva er nevnt i Sverres saga. Hva heter den der?",
    difficulty: "medium",
  },
  {
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "wdmQIz_8Rkjl22d8BkFjZ", text: "New Zealand", correct: !0 },
      { _key: "vEBZytdoIl9NRRA1FDPtQ", text: "Marshalløyene", correct: !1 },
      { _key: "refxvxfBWJnOv4XhqRyCt", text: "Salomonøyene", correct: !1 },
    ],
    _key: "I6b1pmeRkDrK1_0r_mr3N",
    text: "Aotearoa kalles landet av urbefolkningen. Hva kaller vi det?",
  },
  {
    _key: "srNma3_UAxtNaIcrRpM-k",
    text: "Hvilket av disse stedene møtes Dovrebanen og Rørosbanen?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "lJPdTH6j1juABfswKvnex", text: "Støren", correct: !0 },
      { _key: "fgfLqLiWjRx-UoTrNHLrC", text: "Kotsøy", correct: !1 },
      { _key: "5_kMOiJB0tTB1y488fB_u", text: "Berkåk", correct: !1 },
    ],
  },
  {
    _key: "bzkEeAHJGLscQYZlyAeR_",
    text: "I hvilken kommune ligger et innendørs skianlegg som heter Snø?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "hhXrQ4UcNkhW2crEe0yxx", text: "Lørenskog", correct: !0 },
      { _key: "I28-OwSjUl5ZvdS5AZuyo", text: "Snåsa", correct: !1 },
      { _key: "bxLAEFWmU4HtZQYas2aAR", text: "Bærum", correct: !1 },
    ],
  },
  {
    _key: "7WoT7XZCJLCmw7yGRzAsf",
    text: "Hvor er Praia hovedstad?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "b-42OO1xFi612L0-ttz5Z", text: "Kapp Verde", correct: !0 },
      { _key: "eaSU0ySbihjaEYkvMwTqM", text: "Tsjekkia", correct: !1 },
      { _key: "AxW77zhLXw0mK4FGcVZvj", text: "Fuerteventura", correct: !1 },
    ],
  },
  {
    _key: "5n4v4uKnBooPiQXCPPSOL",
    text: "Du bare må kjøpe Espa-boller, men hvilken kommune er du i da?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "N8SmZDpZdOsL3nIKUsqG3", text: "Stange", correct: !0 },
      { _key: "DK-iLZiQUGtTa9fM7YdcP", text: "Trondheim", correct: !1 },
      { _key: "nBvZjYF1Oo_Vbgdf4SUG_", text: "Brumundal", correct: !1 },
    ],
  },
  {
    _key: "FYnP6960pN83U25WpYN_2",
    text: "Arif Murakami vant P3-prisen i fjor. Hvor er han født?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "j83jbJpztnpd0lOnbBVUu", text: "Oslo", correct: !0 },
      { _key: "Kb-xylUkh8fdVrls4wxOE", text: "Zanzibar", correct: !1 },
      { _key: "yX2YSGrMBnH7CAi7daJVb", text: "Drammen", correct: !1 },
    ],
  },
  {
    _key: "GeGIShrWofr7GhBeszHcw",
    text: "Gunnhild Sundli synger i Gåte. Hvor er hun fra?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "kxgWyBb8J_scC55kPMKQk", text: "Storås", correct: !0 },
      { _key: "R0YvA8D5xouH_xqNCvN8v", text: "Trondheim", correct: !1 },
      { _key: "kuGHNONhNyd6oqT3kwqsK", text: "Levanger", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "2yvIDO_faPforxwMFHM19", text: "Jessheim", correct: !0 },
      { _key: "iDeSjupcwrtRIiW7YmIEm", text: "Jevnaker", correct: !1 },
      { _key: "LAPHqx9M37HEdJNKG5Nrt", text: "Nittedal", correct: !1 },
    ],
    _key: "40GdRFK-uWSaI7Lf2GjeO",
    text: "Hvor kommer Emma Steinbakken fra?",
    difficulty: "medium",
    category: null,
  },
  {
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "U9WbO2MNnoJqGNk0IgVzi", text: "Ohio", correct: !0 },
      { _key: "Lfvgj_gtTQUe4T9rWObUR", text: "England", correct: !1 },
      { _key: "EvhWBF6OTiSyG8nBhnVpz", text: "Los Angeles", correct: !1 },
    ],
    _key: "DAxu5kZgleRHs7hc3osc0",
    text: "Dra dit youtuber Logan Paul er fra",
  },
  {
    _key: "Ag4c0GbFEzL9jPh32j8vr",
    text: "Squash blir en ny øvelse i OL i 2028. Hvor kommer sporten fra?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "k5CBG2a2MdpzTYS0Z3aGX", text: "England", correct: !0 },
      { _key: "sO6Cc2XTCKtMDek5GRIJd", text: "USA", correct: !1 },
      { _key: "cDxGmj5DN7EbXocq39S--", text: "Sør-Afrika", correct: !1 },
    ],
  },
  {
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "vdnB0QGgaQNudjSZSXYaX", text: "Oldedalen", correct: !0 },
      { _key: "t_eUeOCiiB4g_nyBEmXRM", text: "Isdalen", correct: !1 },
      { _key: "TjtNBJlr8R3mCPQsLkJG_", text: "Aurlandsdalen", correct: !1 },
    ],
    _key: "hjyWkR8DSCBdlxmlxt6ud",
    text: "I filmen «Fedrelandet» drar Margret Olin med faren til en eventyrlig dal",
  },
  {
    answers: [
      {
        _key: "M4BaUV48PtyEfNs0QQsz_",
        text: "Alta-Kautokeinovassdraget",
        correct: !0,
      },
      {
        _key: "rwvalMs1XQUrruzIvbQv_",
        text: "Pasvikvassdraget",
        correct: !1,
      },
      { _key: "1jLYDS2jiWQ6QZF32eZk1", text: "Tanavassdraget", correct: !1 },
    ],
    _key: "iT-x1Bbv45LFpFfdvSCim",
    text: "Hvilken vassdrag handler det om i «Ellos eatnu – La elva leve»?",
    difficulty: "medium",
    category: null,
  },
  {
    _key: "y3erZR_Dyr-xkNG6WXrJb",
    text: "Hvor skal prinsesse Märtha og Durek Verret gifte seg?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "nVYO_lQyJtFM2BN-wOTNx", text: "Geiranger", correct: !0 },
      { _key: "A8O5fQeT7-hmXeAcOTf6P", text: "Åndalsnes", correct: !1 },
      { _key: "RNiZgCY2k3apVfJ_co4V7", text: "Ålesund", correct: !1 },
    ],
  },
  {
    _key: "YBgSPtcnjPTrI46-xxuQh",
    text: "Hvor finner du Skitbyen?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "YHw89JRbmOGNPe7xPZdDd", text: "Trondheim", correct: !0 },
      { _key: "kGBjgOaP6N2dTEgP0UqXp", text: "Bergen", correct: !1 },
      { _key: "xsB5L7456QDFBdDSrZlK6", text: "Mo i Rana", correct: !1 },
    ],
  },
  {
    _key: "85ZGwzqY5ox3gJUDR_cQa",
    text: "Hvor er FNs internasjonale domstol?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "aG4HYh61ADSq5P1ou6peZ", text: "Haag", correct: !0 },
      { _key: "rQr2e5xk8eQWJZjm4OlRx", text: "New York", correct: !1 },
      { _key: "c_AGxQP66i-l3C-u1xzg7", text: "Geneve", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "oxhprRSdOgINhSGc4SzR3", text: "Tyskland", correct: !0 },
      { _key: "OMBfPjTdCtLaGf8UKmesA", text: "Spania", correct: !1 },
      { _key: "DN404_ZmFMuBbc9dipG_F", text: "Østerrike", correct: !1 },
    ],
    _key: "gp3vBSVYbu4okOPp2w5kr",
    text: "Alois Alzheimer har gitt navn til en sykdom. Hvilket land var han fra?",
    difficulty: "medium",
  },
  {
    _key: "ZonYv8JN7kj9QY3G12euF",
    text: "I krigsfilmen «Konvoi» følger vi et norsk lasteskip i 1941. I hvilket hav?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "1rDgxNl2BknQvYol0u_NU", text: "Nordishavet", correct: !0 },
      { _key: "4dw8lNkDCxM5ENM9oiDM-", text: "Sørishavet", correct: !1 },
      { _key: "yf_ZD0hj0wsJNUeKhkMwc", text: "Stillehavet", correct: !1 },
    ],
  },
  {
    _key: "xK6Vykn35N83wTMT9z_IZ",
    text: "Hvilket fotballag er «Den gule horde» supportere for?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "OpfrCAPfdLQytFjkfxjMS", text: "Bodø/Glimt", correct: !0 },
      { _key: "e6OY3eGxZ8J6-65wWYa2-", text: "Lillestrøm", correct: !1 },
      { _key: "DehZDLOQBEGn43UlqjS9x", text: "Brann", correct: !1 },
    ],
  },
  {
    text: "Bli med Viggo Valle til området han vokste opp",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "DCC7zValZ8FRR_j40C0BF", text: "Lofoten", correct: !0 },
      { _key: "lmfUlsAgsJGZTN1vY-dBO", text: "Sunnmøre", correct: !1 },
      { _key: "pUkOqxaLFRYetL11SIypz", text: "Hvaler", correct: !1 },
    ],
    _key: "wt8iXBcP1AjVP-I5Cw7I8",
  },
  {
    _key: "aTWe-cf-1zmS5KN02r1aV",
    text: "Hvor har Taylor Swift vokst opp?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "P8PZhSCTbhVVrdN3muQG_", text: "Pennsylvania", correct: !0 },
      { _key: "-KrZTpBeczG3YNZp-8nyJ", text: "Nevada", correct: !1 },
      { _key: "d95Y5mEudjVCU0u9qqDMf", text: "Montana", correct: !1 },
    ],
  },
  {
    _key: "auYKi6qk6ShJ2yI0TU7Ey",
    text: "Hvor mottok Taylor Swift sin fjerde Grammy for årets album?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "SFyXbnzP3ao4iOo1qI9Ti", text: "Los Angeles", correct: !0 },
      { _key: "rSTOYTEHWZSHixcmVFOWP", text: "San Francisco", correct: !1 },
      { _key: "RilDFyH5v3cktBRcPB0Ph", text: "Miami", correct: !1 },
    ],
  },
  {
    _key: "MqDABIoEb5cyESgMXUVPt",
    text: "Hvilket fylke representerer Sandra Borch (Sp) på Stortinget?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "ePPbcrLR6yxdYQGVYIoZW", text: "Troms", correct: !0 },
      { _key: "39WrrbLtkif3HTZkVPY7_", text: "Vestland", correct: !1 },
      { _key: "_iEy4tsl2ZUTONWSPF7ai", text: "Finnmark", correct: !1 },
    ],
  },
  {
    _key: "d3kbpig95c3nqWxECd0zy",
    text: "Besøk byen som er Europas kulturhovedstad i 2024",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "7fWItELYKLv1DllJo4Chy", text: "Bodø", correct: !0 },
      { _key: "47_wNWre4lo_2wTcve-bz", text: "Luleå", correct: !1 },
      { _key: "YaLYNtma0n9n9KvW4bU0k", text: "Århus", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "-Ve6bulFbAoW9VwU_NCf4", text: "Ringsaker", correct: !0 },
      { _key: "JtnIErl4i9pMq7O32tyEu", text: "Hvaler", correct: !1 },
      { _key: "YhrfWzDD6dILItX5pCRTe", text: "Hemsedal", correct: !1 },
    ],
    _key: "o-vNe4cCZh5hcU2ixDK2v",
    text: "Dra til Norges største hyttekommune",
    difficulty: "medium",
  },
  {
    _key: "rIMQHIUZJZCNrUlsVmVRH",
    text: "Skyt ballen i mål på Romssa arena, som het noe annet annet inntil i fjor",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "ysDhc8Wj4avdKTWHB23jH", text: "Alfheim", correct: !0 },
      { _key: "XT9e4nqCOEl6hSgUMmhLP", text: "Lerkendal", correct: !1 },
      { _key: "qkl7CCoiKV1f5yPrTZxB0", text: "Høddvoll", correct: !1 },
    ],
  },
  {
    text: "Hvor er Javier Milei president?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "EibbmRJOOZIKrMIBd55A3", text: "Argentina", correct: !0 },
      { _key: "FFWN3Wuai5icCIC5KkizY", text: "Portugal", correct: !1 },
      { _key: "ArFbmoPvS9ETqgPGbWDZE", text: "Brunei", correct: !1 },
    ],
    _key: "aLB3HJsfsZKRDlf9e8RAm",
  },
  {
    category: null,
    answers: [
      { _key: "cphluUc9AZ5B0MLydXsZ4", text: "Hellas", correct: !0 },
      { _key: "kitELy7vbCKvbSJs7EaJC", text: "Georgia", correct: !1 },
      { _key: "fqnCxVnRnLttDGR6RlGEg", text: "Polen", correct: !1 },
    ],
    _key: "-6pkC0nwNm0UfWgbF_f3s",
    text: "Reis til landet som gjorde likekjønna ekteskap lovlig fra februar i år",
    difficulty: "medium",
  },
  {
    text: "Hvor holder hjørnesteinsbedriften Nammo til?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "8tMnu3I5HqChRCLyN0asU", text: "Raufoss", correct: !0 },
      { _key: "GnIhGthHkOrDY70S6A4RN", text: "Hamar", correct: !1 },
      { _key: "xchZAyJYUn8rl7djrZrr-", text: "Hønefoss", correct: !1 },
    ],
    _key: "u63d-vtoEzCVIOTaYQi1m",
  },
  {
    _key: "9wdXaCo4OxbaCz1KwF3tw",
    text: "Hvilken norsk øygruppe er kjent for dun fra ærfugl?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "zaJHFn1aHznYi0kWjOe6b", text: "Vegaøyene", correct: !0 },
      { _key: "cgvR-BRSOtcCb5C47rzi9", text: "Hvaler", correct: !1 },
      { _key: "H4MX2L7aj16L52YFcKEYu", text: "Vikna", correct: !1 },
    ],
  },
  {
    _key: "FnV__90WtV7--8Bw43n8m",
    text: "Hva er Fastlands-Norges største øy?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "ZSegkI9mJR8LgPZsCntlv", text: "Hinnøya", correct: !0 },
      { _key: "cFMc1xoxUKO6FCu148wLd", text: "Sørøya", correct: !1 },
      { _key: "mP-xNAVU9_1kdVVXvJqrf", text: "Karmøy", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "hNXpBGUT5Rcl-19giOoiH", text: "Asia", correct: !0 },
      { _key: "RqZFW809b0CMbxSso14zh", text: "Nord-Amerika", correct: !1 },
      { _key: "-VkKhftupUPvG9SyPo_ZW", text: "Oseania", correct: !1 },
    ],
    _key: "bPFaX97q19IV1euqoQfbJ",
    text: "Rabarbra kom til Norge på 1700-tallet. Hvor kom den egentlig fra?",
    difficulty: "medium",
  },
  {
    answers: [
      { _key: "wurxv7E7MbKb8nnW8g7n5", text: "Sana", correct: !0 },
      { _key: "iMQBW_59dPmkw6KleHOGS", text: "Beirut", correct: !1 },
      { _key: "xzDepS1Ft_P5KRTmKRW1n", text: "Kampala", correct: !1 },
    ],
    _key: "WgKxGodx26rAMbQN9q6SJ",
    text: "Hva er hovedstaden i Jemen?",
    difficulty: "medium",
    category: null,
  },
  {
    text: "Gjør som vikingene og reis til Miklagard. Hva heter byen nå?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "9m_lAhV_l92FA3cj9VWw4", text: "Istanbul", correct: !0 },
      { _key: "RbRNBXoOGbNYVTPmqDoCc", text: "Alexandria", correct: !1 },
      { _key: "SyssHXiuKush7GzJZMZcy", text: "Adrianopel", correct: !1 },
    ],
    _key: "oT15l0IK8b92ah-pA7u7H",
  },
  {
    _key: "UgxS_MJEx5KWYna8SA-WH",
    text: "Hvilket land har 95 prosent av markedet av krydderet safran?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "0b01bXQYxmS06YSnJVsIb", text: "Iran", correct: !0 },
      { _key: "VTHcWfkd7QupltkeC_VdJ", text: "Spania", correct: !1 },
      { _key: "NVWjahiUa26Wj_UD3jPcP", text: "Hellas", correct: !1 },
    ],
  },
  {
    _key: "RDWSkv6WIX3F1ibMZxN5-",
    text: "Hvor ble Pablo Picasso født?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "gW_VOgFE-79_l7O2dwYfw", text: "Malaga", correct: !0 },
      { _key: "uEyXFEODKUTk8lSaLaZXP", text: "Lisboa", correct: !1 },
      { _key: "netpj-73WRTucy6hqatlO", text: "Paris", correct: !1 },
    ],
  },
  {
    text: "Ta på deg solhatt og dra til stedet der rekordvarmen 35,6 grader er målt",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "O-nYA8HY3qyKF2gzwXEgN", text: "Nesbyen", correct: !0 },
      { _key: "XnO26g3I_lTHJNpfDuQAU", text: "Tafjord", correct: !1 },
      { _key: "uD4Mg9zSqa7X0g5L8PRxl", text: "Sunndalsøra", correct: !1 },
    ],
    _key: "sF_MOCQAbY6bPKPwjmTao",
  },
  {
    _key: "Mspklchww3lXlT9zAX-Qn",
    text: "Reis til øya som har halloumi som nasjonalrett",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "h4PmgeA4ZB2WjPVEAhaCF", text: "Kypros", correct: !0 },
      { _key: "xpDopsBBc-COOQtKsu1kq", text: "Thailand", correct: !1 },
      { _key: "AF2kQs9A8wJQvxsTcvR7i", text: "Nederland", correct: !1 },
    ],
  },
  {
    _key: "NLXk_YqQvNQga1hiMKfVG",
    text: "Frites er nasjonalrett i dette landet",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "8-Ni0wUJXOgM65iDZ_d7s", text: "Belgia", correct: !0 },
      { _key: "qxzaOsK3X05kB4ETbPOEJ", text: "Nederland", correct: !1 },
      { _key: "iazMOhw6B_XoBl2x7Zd9q", text: "Frankrike", correct: !1 },
    ],
  },
  {
    _key: "q-3st56fLaEf7dpzbRP-Q",
    text: "Hvor foregår den internasjonale urfolksfestivalen «Riddu Riđđu»?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "cj9Awso-xVpIpYz9cRB4B", text: "Kåfjord", correct: !0 },
      { _key: "RFlz5bQvV7AYYnS-EJZ8t", text: "Malangen", correct: !1 },
      { _key: "W7g3xDZ6krH9dFE1J0vGt", text: "Nordkjosbotn", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "NFXtO0wkS_Fs8VypldKb9", text: "Mogadishu", correct: !0 },
      { _key: "IE5Txu1Iqw4MgVVRalfJ3", text: "Maseru", correct: !1 },
      { _key: "YClFE2kqhQZ9OkMr30Yx4", text: "Maputo", correct: !1 },
    ],
    _key: "f5e-3QUZPp0i5pddIqRB3",
    text: "Hva er hovedstaden i Somalia?",
    difficulty: "medium",
    category: null,
  },
  {
    _key: "PDGjHEanoRmfW4-J4vOtZ",
    text: "Hvor er Addis Abeba hovedstad?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "ETgc5pus8Dvj4IO34bt_w", text: "Etiopia", correct: !0 },
      { _key: "enkFG_y_tJQRjWo24skVm", text: "Eritrea", correct: !1 },
      {
        _key: "HUCuMoxBk3KplPXEcf1bm",
        text: "Ekvatorial-Guinea",
        correct: !1,
      },
    ],
  },
  {
    _key: "0orD_T269oqbEWGNi6wW5",
    text: "Hvilket land produserer mest merinoull?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "wY5_fN4c9SsTyHZNtyiZ5", text: "Australia", correct: !0 },
      { _key: "0gatGgA5tVqZsbZettxxo", text: "Sør-Afrika", correct: !1 },
      { _key: "q7R1NdR2YKci0AAg9rUH1", text: "Chile", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "19O72nG2Et6w8PAAbnLHw", text: "Færøyene", correct: !0 },
      { _key: "Avo4NKERUUxkAwwWHutSL", text: "Orknøyene", correct: !1 },
      { _key: "zhuk8WUihvHVl45mNfux_", text: "Hebridene", correct: !1 },
    ],
    _key: "LLhyIJqyuVrXTXNM1umgE",
    text: "Hvilken øygruppe er Tórshavn hovedstaden i?",
    difficulty: "medium",
  },
  {
    answers: [
      { _key: "Fh7wWiSY1ogSbm9R-5q80", text: "Russland", correct: !0 },
      { _key: "PQteygJkWV2YlmaHgoN4b", text: "Grønland", correct: !1 },
      { _key: "QuU97mVwQpksMugwulipl", text: "Mongolia", correct: !1 },
    ],
    _key: "OZmx8neMdwMgC0biRbZVx",
    text: "Ojmjakon og Verkhojansk er verdens kaldeste bebodde steder. Hvilket land?",
    difficulty: "medium",
    category: null,
  },
  {
    _key: "2NGJtrxNA428zWKcgf8Jg",
    text: "Du seiler fra Det karibiske hav gjennom Panamakanalen. Hvilket hav kommer du til?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "sB1ZpAisjcNkdiDsW7FhA", text: "Stillehavet", correct: !0 },
      { _key: "i21d_ABbMEq1CWZFUTacn", text: "Rødehavet", correct: !1 },
      { _key: "OIkr0WXVlZy5uHYKbOXQN", text: "Dødehavet", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "cLzDfden0m4peGc2WM2mJ", text: "Tigris", correct: !0 },
      { _key: "3uXTWrU9-ldSBH8GUICXr", text: "Eufrat", correct: !1 },
      { _key: "N8F_aPwTfuWai3hZAKrmO", text: "Zab", correct: !1 },
    ],
    _key: "6hWZL3EOralKF_jbxLP6f",
    text: "Hva heter elva som renner gjennom Bagdad?",
    difficulty: "medium",
    category: null,
  },
  {
    _key: "9EpRHb1oQ3jMr8I-zqNHm",
    text: "Hvilken er størst av de åtte Kanariøyene det bor folk på?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "53NWEg5emsfjJmAIZMrip", text: "Tenerife", correct: !0 },
      { _key: "8BUXtwIlUt5cGID7PARTs", text: "Gran Canaria", correct: !1 },
      { _key: "GsTnfvdrqa6ebjA0AELcX", text: "Fuerteventura", correct: !1 },
    ],
  },
  {
    _key: "2kuUEatunX0lSaS92163i",
    text: "Petter Dass skal ha gitt navn til en fjellformasjon i Nordland. Hvilken?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "f8gyWbuX1qNpHqqErR1q5", text: "De sju søstre", correct: !0 },
      { _key: "r3osdFooSThvs_-xoSGh9", text: "Torghatten", correct: !1 },
      { _key: "4Z5Aa6e8TkFcX_urBwEvY", text: "Himmeltinden", correct: !1 },
    ],
  },
  {
    text: "Ta med deg hundespannet og still til start i Femundløpet. Hvor?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "GCDLvf9SS4S-oegKXmDH-", text: "Røros", correct: !0 },
      { _key: "cxYq4gDIE1GZW9jBrt_9U", text: "Tynset", correct: !1 },
      { _key: "wyx-qVARMEa9NtV2qCoGu", text: "Holtålen", correct: !1 },
    ],
    _key: "o7ZSNVTju0ohxvIw71l8q",
  },
  {
    _key: "2-EZTwUxk0P_9XUCeNNsr",
    text: "Hvor snakker de lao?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "vKojmDu5vU52dvZ46hImH", text: "Laos", correct: !0 },
      { _key: "7eDhMOxgU_uDE5TalonU9", text: "Libya", correct: !1 },
      { _key: "vulumCUSocoEHtLF6G703", text: "Lesotho", correct: !1 },
    ],
  },
  {
    _key: "aSpkJTqZCUvrgYtm-y67f",
    text: "Reis med den transsibirske jernbanen fra Moskva og bli med til siste stopp",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "Le87MhNkbpVucOFNdF9bQ", text: "Vladivostok", correct: !0 },
      { _key: "kzNZ-PwacQ9buRf2Yfy_H", text: "Beijing", correct: !1 },
      { _key: "vq7Eq0jmOjrP0hqmKGhjG", text: "Istanbul", correct: !1 },
    ],
  },
  {
    _key: "72ZCufiwX9upuEPsGAvnl",
    text: "Hvilket land kommer roquefort fra?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "hGMFtHBSfBP5wEP8Dmsj_", text: "Frankrike", correct: !0 },
      { _key: "rsgcLHzp6yl2jRcXbW7qz", text: "Nederland", correct: !1 },
      { _key: "QRlqj58sbcGz6CfHWpoVh", text: "Italia", correct: !1 },
    ],
  },
  {
    _key: "hLUMRCiSGHQvxyMftvpJW",
    text: "Hvilket land kommer gorgonzola fra?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "qYpIRUORtdlePSKwrf-M-", text: "Italia", correct: !0 },
      { _key: "Gxc5DU3UPVvts5lVE2DVM", text: "Frankrike", correct: !1 },
      { _key: "ScK6M4aHw8kNqR6v7J1ml", text: "Ungarn", correct: !1 },
    ],
  },
  {
    _key: "T1a5CwcsBzwi4s8k8C1bY",
    text: "Hvilket land har flest steder på UNESCOs verdensarvliste?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "qeNm3iLudrH78XK_3nl3K", text: "Italia", correct: !0 },
      { _key: "ynHJrPNrG2355C_16ZFoP", text: "Frankrike", correct: !1 },
      { _key: "G9TeRIvz-IAsHCMgGvg2w", text: "Russland", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "bhx7OTi9DTgpBLnNCcdCF", text: "Mora", correct: !0 },
      { _key: "t3nARUS-jzwMes5vcM-su", text: "Visby", correct: !1 },
      { _key: "PpLCnc0sbf1the2Vr7y8V", text: "Kvikkjokk", correct: !1 },
    ],
    _key: "kl2qqyLBkUoUBLJsdwRaN",
    text: "Ta på deg skiene og gå Vasaloppet. Hvor kommer du i mål?",
    difficulty: "medium",
  },
  {
    _key: "JgoZHyFwWbMR9II6anZ0O",
    text: "Du vil besøke Eremitasjen som verdens største museum i areal. Hvor drar du?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "meNuuWpugd4EaSj863Mhz", text: "St. Petersburg", correct: !0 },
      { _key: "zC5ngv8Ojc4DoF3yJmsUt", text: "Sofia", correct: !1 },
      { _key: "5iOQne5RX6VBjkGcfGnKK", text: "Dresden", correct: !1 },
    ],
  },
  {
    _key: "J9JXBdq0v4B_464JNFewr",
    text: "Hvor finner du bydelen Rinkeby?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "hKanMwJ8LKYPn-RZ9acpW", text: "Stockholm", correct: !0 },
      { _key: "QD9xCdqskNUIpuRccNlnJ", text: "København", correct: !1 },
      { _key: "MZeL6w_u0Ui8uWmioaBtP", text: "Malmø", correct: !1 },
    ],
  },
  {
    text: "Hvor finner du Norges miljø- og biovitenskapelige universitet?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "5xZeMcpib0_JrPF9R66YR", text: "Ås", correct: !0 },
      { _key: "KjOUpPmZRyjgXJYkFoMGH", text: "Moelv", correct: !1 },
      { _key: "RiAvPr0L2yo1b0xRbU6vH", text: "Ytre Enebakk", correct: !1 },
    ],
    _key: "8_y4rP9mCJCcTonbsSx7P",
  },
  {
    answers: [
      { _key: "usfgHjo1hPmU_rzxKnNt7", text: "Tarifa", correct: !0 },
      { _key: "ymq2cA6CcO8U1enLTv5Ar", text: "Faro", correct: !1 },
      { _key: "R90UJIoBmvojgSk6r3wv3", text: "Areopoli", correct: !1 },
    ],
    _key: "b6AJYN4n8Tnt6I9_9yLMR",
    text: "Dra til det sørligste fastlandspunktet i Europa",
    difficulty: "medium",
    category: null,
  },
  {
    answers: [
      { _key: "ZLNW50Ji3b8N35ovcS9p2", text: "Portugal", correct: !0 },
      { _key: "d_ytRg0d0GZQ5j_qPCfWI", text: "Spania", correct: !1 },
      { _key: "KO7Hfbi6xoTOo2nFxp9Kk", text: "Frankrike", correct: !1 },
    ],
    _key: "Hvx690sNACHnCxpVogtkk",
    text: "Asorene er ei øygruppe i Atlanterhavet. Hvilket land tilhører de?",
    difficulty: "medium",
    category: null,
  },
  {
    _key: "V0tr49Fmz_LYS1JkVjC5I",
    text: "Et område i Trondheim, et slott i Danmark og et tidsskrift deler dette navnet",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "lNukkIir6CxxboAxpwblu", text: "Sorgenfri", correct: !0 },
      { _key: "QsAoohF9RymmIBR5616Xn", text: "Enerhaugen", correct: !1 },
      { _key: "iMEL678LDfcbAwdQ2Hd1d", text: "Tasta", correct: !1 },
    ],
  },
  {
    _key: "yRMzgDE8OPhD8jkxUX-fU",
    text: "Reis til verdens smaleste sjøpassasje som benyttes for internasjonal skipsfart",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "dgEnN0bYdUkf02pkj9ec1", text: "Bosporosstredet", correct: !0 },
      {
        _key: "4XmBwF_yEY_iIMk-MoQWo",
        text: "Gibraltarstredet",
        correct: !1,
      },
      { _key: "lZfQw0zi7pNR4rQ0VwqIm", text: "Hormuzstredet", correct: !1 },
    ],
  },
  {
    text: "Du viser din nye film på festival og får «Gullbjørnen». Hvor?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "RbMoICQzWMaInnUcWV0jo", text: "Berlin", correct: !0 },
      { _key: "8sRcR7Av4dIUwC38uYbt0", text: "Longyearbyen", correct: !1 },
      { _key: "TUVbkWHYD6cZmg4qRS21f", text: "Tromsø", correct: !1 },
    ],
    _key: "LuCHpkEi9N9Dhc-PFKTBD",
  },
  {
    _key: "ocsH0BD5s7uXKl0dQ3XlG",
    text: "Hvor kommer avisa «The Guardian» ut?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "eV0f4d0Ak9ATxCoy_0sCv", text: "London", correct: !0 },
      { _key: "UFrlOxxUTdpVq3VmeWf_i", text: "New York", correct: !1 },
      { _key: "n0JyBsNr2elQPn0TXcmYY", text: "Zürich", correct: !1 },
    ],
  },
  {
    _key: "RG8hOIrH_3R0UCt2kbbXQ",
    text: "Bank på døren på hovedkvarteret til Spotify i denne byen",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "wh0VOhTu7B3sedq-fAmcL", text: "London", correct: !0 },
      { _key: "mNMZfCCcDDyk4YbAY9Mpw", text: "San Francisco", correct: !1 },
      { _key: "_eBOcdXW56R09lcg6Qm67", text: "Stockholm", correct: !1 },
    ],
  },
  {
    _key: "9a6EBy_G9W2guf9iz8_dc",
    text: "Hvor kan du møte på ville nebbdyr?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "1LQHzBVxoQrjp-L0Cw9YP", text: "Australia", correct: !0 },
      { _key: "9IYL-TchZDazDNXuiw39G", text: "Japan", correct: !1 },
      { _key: "ZjaWMiZWrgY_47caw1pfJ", text: "Nepal", correct: !1 },
    ],
  },
  {
    _key: "xHIXq2_rMcT-1SNqwhzx2",
    text: "Hvor starta Bundadsgeriljaen arbeidet for gode fødetilbud i distriktene?",
    difficulty: "medium",
    category: null,
    answers: [
      { _key: "W75p6ji6hI4Q_YwchM4B7", text: "Kristiansund", correct: !0 },
      { _key: "thso2IfLg6FvV-GI6MyhX", text: "Sortland", correct: !1 },
      { _key: "P1rhHZ9oQ6OyNTfr6_mNY", text: "Måløy", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "94QDybiWa01AgYV2OGJ3F", text: "India", correct: !0 },
      { _key: "ZbiLWccmrm2SnP2kAPxSx", text: "Tanzania", correct: !1 },
      { _key: "3aea57CXb2YMMoCSL2CRV", text: "Paraguay", correct: !1 },
    ],
    _key: "OpyvQq8YBd5xazyPT9o_Z",
    text: "I hvilket av disse landene lever vill bengaltiger?",
    difficulty: "medium",
    category: null,
  },
  {
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "45Ds8TaRswpbPHs9VKv2L", text: "Raet", correct: !0 },
      { _key: "aQ-73c1DKkrf2_9VmmT6G", text: "Jomfruland", correct: !1 },
      { _key: "q6glXAqinsb6Xac6Fpdip", text: "Ytre Hvaler", correct: !1 },
    ],
    _key: "1rXOFV5cL55EGUbZE4G_g",
    text: "Hva er vår sørligste nasjonalpark?",
  },
  {
    _key: "C6Dv_SNSSyFRF0sQfBZlW",
    text: "Bli med forfatter Tore Renberg på byvandring i hans by",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "8oNqP3C2dzoCGOXcPCQDE", text: "Stavanger", correct: !0 },
      { _key: "JthCZ3iYvtCB9LXUSIcYp", text: "Kristiansand", correct: !1 },
      { _key: "qvJ3tOhn2qsow5-3OAOhO", text: "Bergen", correct: !1 },
    ],
  },
  {
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "sAU6K65GUa69-EAwBGU_G", text: "Portugal", correct: !0 },
      { _key: "TFVYUZL_0HwtEu8RbqjEq", text: "Belgia", correct: !1 },
      { _key: "fPT9yatolR5Rmsdgq0ECr", text: "Argentina", correct: !1 },
    ],
    _key: "ITHH8meu43FOvulCmWiSo",
    text: "António Guterres er FNs generalsekretær. Hvilket land er han fra?",
  },
  {
    category: null,
    answers: [
      { _key: "w_gXPW5sPWgmXAntQXDuD", text: "Karmøytunnelen", correct: !0 },
      {
        _key: "ZVjN4Vy4P-zLcC_DtBraE",
        text: "Bømlafjordtunnelen",
        correct: !1,
      },
      { _key: "AFMnbkjlt1RPCw4KpCZpc", text: "Hitratunnelen", correct: !1 },
    ],
    _key: "Rif_Pk4Hun98K_6AYosha",
    text: "Hva er Norges nest lengste undersjøiske veitunnel",
    difficulty: "hard",
  },
  {
    _key: "WL9cyDDjFOfwrfJGqFVTS",
    text: "Hva heter slusen i Telemarkskanalen som har fem løftekamre?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "vt7gaQ7_TwHaTaB5v6JjL", text: "Vrangfoss", correct: !0 },
      { _key: "HGfwCUeJiTivEUGzhL5S4", text: "Løveid", correct: !1 },
      { _key: "XqpkvINNvC9a33gAGkw13", text: "Eidsfoss", correct: !1 },
    ],
  },
  {
    _key: "VNBBbLXqkOIUex7oSq-1i",
    text: "Bli med til stedet skiløperen Maiken Caspersen Falla er fra",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "ZRNnqFfT_Nz42OIj-PLdm", text: "Fetsund", correct: !0 },
      { _key: "eNdGgWvif_gu2vOVF4a5B", text: "Blaker", correct: !1 },
      { _key: "TeoF89eEd4hXYvnVIWL5q", text: "Lørenfallet", correct: !1 },
    ],
  },
  {
    _key: "8x-iYnCddOuKtHSR2ufF6",
    text: "Hva heter kanalen som går tvers gjennom Lindesnes-halvøya?",
    difficulty: "hard",
    category: null,
    answers: [
      {
        _key: "qaPgwkVqHz_0vjX0sFZlX",
        text: "Spangereidkanalen",
        correct: !0,
      },
      { _key: "DehuXXN_GP1Ar9zBccyKn", text: "Røyksundkanalen", correct: !1 },
      { _key: "-NojBugJGDjVWtRHZKS6Y", text: "Kassenkanalen", correct: !1 },
    ],
  },
  {
    _key: "VwVmYliQMc5IiYYHS4lSk",
    text: "I hvilken kommune renner elvene Nausta, Gaula, Anga og Jølstra?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "SrKqjf_xUrm-d1zdRKFg5", text: "Sunnfjord", correct: !0 },
      { _key: "eMajSyC4MKnL7tQRxtQ-Y", text: "Midtre Gauldal", correct: !1 },
      { _key: "kuKiu0C-OTsfvkL5MOk0w", text: "Målselv", correct: !1 },
    ],
  },
  {
    text: "St. Sunniva rømte til sjøs for å slippe å gifte seg. Hvor drev hun i land?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "MAc-MzhmxCtmtYHxjASIY", text: "Selja", correct: !0 },
      { _key: "TZeEL_YSK4Wv6t1i6zMri", text: "Runde", correct: !1 },
      { _key: "AdV6cdasYSk_gwcp-2tu4", text: "Grip", correct: !1 },
    ],
    _key: "ZVIPE7sQo8Mpr9UEV__cC",
  },
  {
    _key: "sslDu_j-gkYM_Lf_ELvfM",
    text: "Bli med Metteson til hans fødeby",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "_OqypMok8ioitFf3UZF-x", text: "Moss", correct: !0 },
      { _key: "6enMZApk34bcKV9eBALU1", text: "Fredrikstad", correct: !1 },
      { _key: "CP7OOMFBAp0QGs-MwJmQR", text: "Nesodden", correct: !1 },
    ],
  },
  {
    text: "Hvor er hun som lager serien «Tegnehanne» fra?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "YF-U2jax5B26VLxZtPlN1", text: "Kværnaland", correct: !0 },
      { _key: "3ge5WfBhlXC71mgaQEGiq", text: "Flåm", correct: !1 },
      { _key: "CXw4q3OWagRyC_G5jXG7l", text: "Osa", correct: !1 },
    ],
    _key: "a8Q8RrMVuBSi7ne-P-uIu",
  },
  {
    text: "Stortingspresident Masud Gharahkhani har vokst opp her",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "vX_DwSk0MVAi69180t1vb", text: "Skotselv", correct: !0 },
      { _key: "J8zaoVWsqtWt2d7WCaXiW", text: "Kongsberg", correct: !1 },
      { _key: "DWopfKaB7eoTMWAPVdeBn", text: "Hokksund", correct: !1 },
    ],
    _key: "VSoAzOL3x6xro_Q9nHLKJ",
  },
  {
    _key: "L9NmiJhMLd851mIJSxuFZ",
    text: "Jens Haugland sykler for laget Uno-X. Hvor er han fra?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "DyxRclT4dm_JvjyvEiy9J", text: "Rørvik", correct: !0 },
      { _key: "jBomyW8_bB5HJYjnAGLDM", text: "Røyrvik", correct: !1 },
      { _key: "gYy8i_ivQMkTkmHU79L4-", text: "Røyken", correct: !1 },
    ],
  },
  {
    text: "I filmen «Sulis 1907» samler gruvearbeidere seg til et historisk møte. Hvor?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "NKatbTI2TSuuzfpcnHZKB", text: "Langvannsisen", correct: !0 },
      { _key: "FvPAaRgm8bmLLEe1_tG9t", text: "Djupvannsisen", correct: !1 },
      { _key: "L2HtbR7DuiOFexgKhZosK", text: "Balvatnsisen", correct: !1 },
    ],
    _key: "kcOXCTLHvUGhmnJ0C8oNP",
  },
  {
    answers: [
      { _key: "ugzttkhRF6yCMu8YqBiaI", text: "Butangen", correct: !0 },
      { _key: "33w_VWPjKQUIzTYQsXKTl", text: "Fåvang", correct: !1 },
      { _key: "AfpOY_uN0PQnVkjAt-n-X", text: "Hundorp", correct: !1 },
    ],
    _key: "QEspsZf5yMA1jVrNiypjH",
    text: "Dra til bygda Lars Mytting har skrevet om i «Søsterklokkene»",
    difficulty: "hard",
    category: null,
  },
  {
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "k63MPAL4mOo390cHkz_kc", text: "Iran", correct: !0 },
      { _key: "gaR5rMfXS1qZVz33eJXBm", text: "Irak", correct: !1 },
      { _key: "jCUVnWww060ppo79ePubp", text: "Qatar", correct: !1 },
    ],
    _key: "ZM70hf8grLO9Amn2ZW_By",
    text: "I hvilket land foregår «Kvinne, liv, frihet»-protestene?",
  },
  {
    _key: "dMT5DGra-r5xGxP5ez8rh",
    text: "Her er verdens største cruiseskip «Icon of the Seas» bygd?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "cXiIF6RlT6XETYquPHGkD", text: "Finland", correct: !0 },
      { _key: "LTjrYC-7kwWeQdl6CYJYX", text: "USA", correct: !1 },
      { _key: "764Pt1wWUtU2hCJ8mfmKc", text: "Nederland", correct: !1 },
    ],
  },
  {
    _key: "FjIj1fW3ALF9id2PWPedu",
    text: "Bli med Jens Kvernmo hjem til dalen han er fra",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "yOuNWFAmdIfu4ScTgyXyL", text: "Ogndal", correct: !0 },
      { _key: "SsLl-T5ONcQAMRUVfnJWZ", text: "Haltdalen", correct: !1 },
      { _key: "qqoVfvwSiwV-LIj5VdsAr", text: "Stjørdal", correct: !1 },
    ],
  },
  {
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "xU-K6pC_mb3olCTzqDN1N", text: "Nøtterøy", correct: !0 },
      { _key: "iZKDntiWN6YsMvL6YC51n", text: "Notodden", correct: !1 },
      { _key: "AW5glnx4RLk408GO_8J-9", text: "Drammen", correct: !1 },
    ],
    _key: "Ek-K_pfVQC6DGSoxiGOa6",
    text: "Hvor er Kathrine Thorborg Johansen fra serien «Makta» født?",
  },
  {
    text: "Her kan du stille til start i «Arctic Race of Norway» i august",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "akEwDVfKk5ZGNP56f8PwF", text: "Bodø", correct: !0 },
      { _key: "iJoLF2AY2I7oJVrXlziBN", text: "Namsos", correct: !1 },
      { _key: "10FHhKPlI0n0lN3tU3K5c", text: "Fauske", correct: !1 },
    ],
    _key: "ZuSTl0PB2Zc05nr47Ntk_",
  },
  {
    answers: [
      { _key: "U1LWEusaedu9wE82hm5iw", text: "Inderøy", correct: !0 },
      { _key: "lPID152wiK3LRni3Hkgf7", text: "Smøla", correct: !1 },
      { _key: "1WTpwz3sPUkwGCv4KKaOc", text: "Moskenes", correct: !1 },
    ],
    _key: "qMiDueNfpiIglVvIXdcwy",
    text: "Nidelven Blå ble kåra til verdens beste ost i 2023. Hvor blir den laga?",
    difficulty: "hard",
    category: null,
  },
  {
    text: "Hvor vokste kongen Magnus Lagabøte opp?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "Zi8YTuUJ3BnGPoSSfnT9E", text: "Bergen", correct: !0 },
      { _key: "cV2dY6VIRAIeUdB-qkyNA", text: "Irland", correct: !1 },
      { _key: "v8E0IceFAa8hMyxM52Vx2", text: "Island", correct: !1 },
    ],
    _key: "KVM9zVQAyyfVviVuYwyUn",
  },
  {
    _key: "8wOLHmm5e3JG9l5gexaxm",
    text: "Bli med Silje Nordnes til stedet hun er oppvokst",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "8C0MjgtCrrbMGFvagRvmI", text: "Hamarøy", correct: !0 },
      { _key: "7xFj53Ojh_brsQsZlnB4E", text: "Kokelv", correct: !1 },
      { _key: "dEjbA3xxah5NjlfXcgCrI", text: "Kvaløya", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "dPZb-9xSBoQqs3y6awuVn", text: "Rogaland", correct: !0 },
      { _key: "bGxYl78xQ-S_xKcPMpziM", text: "Oslo", correct: !1 },
      { _key: "j4bbVazE8_sImbuZMuRa5", text: "Buskerud", correct: !1 },
    ],
    _key: "b9ZNmJ1mFGkV3V4Yc1q85",
    text: "Tina Bru sitter på Stortinget for Høyre, men for hvilket fylke?",
    difficulty: "hard",
    category: null,
  },
  {
    _key: "pFFdguCmrgwQs4_9k8Usf",
    text: "Bård Hoksrud sitter på Stortinget for FrP. Hvilket fylke er han innvalgt fra?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "NhqEGm5zGy440kEd0pPIn", text: "Telemark", correct: !0 },
      { _key: "tV_IoVBG0mfR5Fx63ytTi", text: "Buskerud", correct: !1 },
      { _key: "KsAZCilZ3iyPZELnCXZM9", text: "Akerhus", correct: !1 },
    ],
  },
  {
    _key: "2Vt3RcQuE-aXqVS4MxVq6",
    text: "Kristin Harila har verdenskord i å bestige høye fjell. Hvor er hun fra?",
    difficulty: "hard",
    category: null,
    answers: [
      {
        _key: "4xrvdklTU-6xHCyY651CC",
        text: "Vestre Jakobselv",
        correct: !0,
      },
      { _key: "orUXOjHkN_xN3NaCofe2j", text: "Glomfjord", correct: !1 },
      { _key: "nStiRQors-aFGjnGKq8pf", text: "Hemnesberget", correct: !1 },
    ],
  },
  {
    _key: "KQj3UlNmZZG8NXZwDJNAu",
    text: "Hvor hadde filmen «Ibelin» premiere?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "Cm4063_vZYXDpLdqVO_CO", text: "Tromsø og USA", correct: !0 },
      {
        _key: "4Cht7ivF9mn3MC884B1u_",
        text: "Trondheim og Frankrike",
        correct: !1,
      },
      {
        _key: "64lmBfeu5iJnVhIiiCuFW",
        text: "Oslo og Tyskland",
        correct: !1,
      },
    ],
  },
  {
    _key: "K80quhduCeXyLbf0kH1sd",
    text: "Taylor Swift skal bare ha konsert i én by i Sørøst-Asia, hvilken?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "Y-8CLdg7U1LVrZ_LqcAGz", text: "Singapore", correct: !0 },
      { _key: "8Q7Ec1FTaaBYa_CVXaBsN", text: "Bangkok", correct: !1 },
      { _key: "GYPoUawfYZf1Jl22Z9qdQ", text: "Hanoi", correct: !1 },
    ],
  },
  {
    _key: "AQQvCnMLWi07Ha2V3awQU",
    text: "Ta på deg gode sko og bestig Sveriges høyeste fjell",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "Jn0NdpWCOj7nf_I_4mhk7", text: "Kebnekaise", correct: !0 },
      { _key: "RNDl-0PY6Pw6fxQBKE-V4", text: "Åreskutan", correct: !1 },
      { _key: "vS11g-hpMfDZsetBuF_CA", text: "Bårddetjåhkkå", correct: !1 },
    ],
  },
  {
    _key: "aZZdTdTtAWxnZ9IP27Clj",
    text: "Hva er verdens mest forurensa by?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "_XIQwBoi8fX47Fgryli7p", text: "Dehli", correct: !0 },
      { _key: "g4ZHy24He7wMD-UnNarcX", text: "Oslo", correct: !1 },
      { _key: "I3e-bLHMrA8-9bOVFLtx5", text: "Los Angeles", correct: !1 },
    ],
  },
  {
    text: "Hva er den lengste jernbanetunellen i Norge?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "qOatcSDKPvad_PnCWM80e", text: "Blixtunellen", correct: !0 },
      { _key: "ST-pmSJv0NpjdIQCkmoKZ", text: "Romeriksporten", correct: !1 },
      { _key: "YfxOb12uSRUIssNw7SDGX", text: "Finsetunellen", correct: !1 },
    ],
    _key: "OOd4tWfcp3Qc9MP6T7N3k",
  },
  {
    answers: [
      { _key: "jZbMa_C4EFWrBlMvfWzFY", text: "Spitzbergen", correct: !0 },
      { _key: "UAf1nshSt0cdSls378Y-z", text: "Nordaustlandet", correct: !1 },
      { _key: "LsVf7DJWW3djMVLRjoPaB", text: "Barentsøya", correct: !1 },
    ],
    _key: "isn3gTZMyPZfG0xw50YQD",
    text: "Hva er Svalbards største øy?",
    difficulty: "hard",
    category: null,
  },
  {
    answers: [
      { _key: "Sy9YAizl4yb-oS74LMvWT", text: "Haparanda", correct: !0 },
      { _key: "1Aea-EDcIM18lKdxAJHEE", text: "Pajala", correct: !1 },
      { _key: "g7nwB7OZYvFrPl1esr0oy", text: "Karesuando", correct: !1 },
    ],
    _key: "tj214hPtJkEBjUtqebEoS",
    text: "Hva er Sveriges østligste by?",
    difficulty: "hard",
    category: null,
  },
  {
    text: "Hvor ligger Harbakhula?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "GLKe6IBkwL42ovwM6JgQ0", text: "Åfjord", correct: !0 },
      { _key: "isCQUYGLXjCb8Fyl7JfVS", text: "Askøy", correct: !1 },
      { _key: "0nen9389T_tMdoP5mm4MC", text: "Øksnes", correct: !1 },
    ],
    _key: "qJW-wHlassMLoyMBAiAu8",
  },
  {
    _key: "GbvbpbpI8nslW8xNE0yvi",
    text: "Kongekrabbe finnes langs kysten fordi arten ble satt ut i en fjord. Hvilken?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "ckfDO03kWZdLY9Krz9gc2", text: "Murmanskfjorden", correct: !0 },
      { _key: "N2Q6NfLXIuXw3_6YoLtUX", text: "Varangerfjorden", correct: !1 },
      { _key: "lFHRGhRaVzKG8q7735mlm", text: "Båtsfjord", correct: !1 },
    ],
  },
  {
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "9t2LcHHxdkPhaqk-0MVF4", text: "Accra", correct: !0 },
      { _key: "UtdkGKRKLlYPsAzFD9Pt2", text: "Monrovia", correct: !1 },
      { _key: "QtO4235Dz_-jSagNjcTrg", text: "Banjul", correct: !1 },
    ],
    _key: "7roRYStS-M_1XTiVmrjyo",
    text: "Hva er hovedstaden i Ghana?",
  },
  {
    answers: [
      { _key: "V5nsWOshS3FADcW76VnCH", text: "Vigelandsparken", correct: !0 },
      { _key: "jmNSPAeAmhr7bnmYL3t3J", text: "Ekebergparken", correct: !1 },
      { _key: "7HS7xCbg2yGzxSNGZOB3G", text: "Muustrøparken", correct: !1 },
    ],
    _key: "saFIlq8ghqON_bRDm8-cZ",
    text: "Dra til parken du kan se skulpturen «Livshjulet»",
    difficulty: "hard",
    category: null,
  },
  {
    answers: [
      { _key: "FWs1WPn3PBoRrVR0pXeCJ", text: "Sør-Afrika", correct: !0 },
      { _key: "xWIoK5HgyENUd7hnPEwUS", text: "Botswana", correct: !1 },
      { _key: "XClxV0aQRBNNjUpiRYYa3", text: "Angola", correct: !1 },
    ],
    _key: "aeHf6Sl-eJc-_OqFlVwUq",
    text: "Hvor foregikk boerkrigene?",
    difficulty: "hard",
    category: null,
  },
  {
    _key: "UOqvrwDG6Nwu05_tL31bd",
    text: "Hvor kan du besøke Trollkyrkja?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "nPWbxe7DOccBn1k0FudVG", text: "Fræna", correct: !0 },
      { _key: "lg4GvAbI-qqHo_EEy-pEX", text: "Titran", correct: !1 },
      { _key: "AP-_zYcj-NjHvKHIux3dK", text: "Indre Nore", correct: !1 },
    ],
  },
  {
    _key: "TeJU8gGbg1eA06z1KCrsz",
    text: "Ta et stykke pavlova der kaka er nasjonalrett",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "-woSPFiDLtTNYHO9NJWM6", text: "New Zealand", correct: !0 },
      { _key: "yqc9GUiOCBt54LvSj0GiC", text: "Russland", correct: !1 },
      { _key: "m3YZS8aNzAun_RdEBwF_t", text: "Nederland", correct: !1 },
    ],
  },
  {
    text: "På norrønt het byen Kœnugarðr. Hva heter byen i dag?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "8cjb6NCjVjU8odvg18QCM", text: "Kyiv", correct: !0 },
      { _key: "KwoWBo4dsF_onay2t2igu", text: "Kherson", correct: !1 },
      { _key: "2fm9C1vUPnFzpLwCXD9bW", text: "Kharkiv", correct: !1 },
    ],
    _key: "KGzr8gcUF_5itwchXPpD9",
  },
  {
    category: null,
    answers: [
      { _key: "iL4WZdrlse_xZwyUYQjuA", text: "Tibet", correct: !0 },
      { _key: "Y4q39aXFok00GygBG8X7B", text: "Bhutan", correct: !1 },
      { _key: "7r0rTGqPQGFdV5rGbyoX7", text: "Nepal", correct: !1 },
    ],
    _key: "Z84U6HJcTcl9uEd8tumfa",
    text: "Hvor er Lhasa hovedstad?",
    difficulty: "hard",
  },
  {
    _key: "VVb94XN2dF-bRnJX50uMZ",
    text: "Ta på deg gode sko og gå Samaria-ravinen. Hvor er du da?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "ZBRMzPEyjbn_ofIYIHZCY", text: "Kreta", correct: !0 },
      { _key: "bm7qSvEMIB2oH3FZ9H6Jq", text: "Korfu", correct: !1 },
      { _key: "mKFpVcS6T2P33ukpHuRfe", text: "Kos", correct: !1 },
    ],
  },
  {
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "bj7kOQkYN34pAjKidVa2S", text: "Oman", correct: !0 },
      { _key: "hLv6tpa0IkQ0pHlVaNK-4", text: "Jemen", correct: !1 },
      { _key: "mCLGzhWfIc2d5GXHhaSkG", text: "Kuwait", correct: !1 },
    ],
    _key: "OTqqCmcplanaaB1_I27xr",
    text: "Hvilket land kommer du til om du drar til Muskat?",
  },
  {
    text: "Hvor må du dra for å oppleve fuglen kivi?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "npGewW5ua7EiRuk59oDfE", text: "New Zealand", correct: !0 },
      { _key: "RNGoALDDT7mDE6vuaQAuW", text: "Sri Lanka", correct: !1 },
      { _key: "IpdlC6b4hViKWW_XoFG6C", text: "Kambodsja", correct: !1 },
    ],
    _key: "QTD_2sEdQbwm_UgAa2IbM",
  },
  {
    _key: "TsHLu6rjgpXFgcVw-HLIT",
    text: "Hvilken nasjonalpark var Norges første?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "RGb7vk66So7Ty2e7JcvPX", text: "Rondane", correct: !0 },
      { _key: "KxVw5BqL6MCitzT4w8xMd", text: "Rago", correct: !1 },
      { _key: "D8Q6Z-nryDojXheIc7O9j", text: "Jostedalsbreeen", correct: !1 },
    ],
  },
  {
    _key: "QC7RCMIQvmsymMIZy_OWF",
    text: "Hvor snakker de marathi?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "jWwENXPXer7Aypu_T1W0B", text: "India", correct: !0 },
      { _key: "9ejZpnL83QMJvvxJW2nky", text: "Kina", correct: !1 },
      { _key: "AsUZXp8DBEhOd-2wPAzTk", text: "Nepal", correct: !1 },
    ],
  },
  {
    _key: "rPHKrJ9fF_64ORmJ9auxc",
    text: "Det første samelandsmøtet var i 1917. Hvor ble det holdt?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "yd0wjq_yds5svUuQwSFfa", text: "Trondheim", correct: !0 },
      { _key: "tR6tl6cdHzKrHYZ2RxpdZ", text: "Karasjok", correct: !1 },
      { _key: "4FQxnlFJYTWWYnedb23AT", text: "Brekken", correct: !1 },
    ],
  },
  {
    _key: "pyg1KgveL3ponad-l1dCC",
    text: "Tordenskiold ble en stor helt etter et sjøslag. Hvor sto slaget?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "AHrddGHnaW41DqzUBYnFy", text: "Dynekilen", correct: !0 },
      { _key: "lVCRjv7qiJkky8HLHD95R", text: "Skjebergkilen", correct: !1 },
      { _key: "CXh3Cm-zbDLZf913utMc3", text: "Lysekilen", correct: !1 },
    ],
  },
  {
    _key: "1lr6w-hhFD8TO4hReTDFv",
    text: "I hvilken hovedstad finner du bydelen Vanløse?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "ysDqgnocKPZvMDfmhg3FR", text: "København", correct: !0 },
      { _key: "9-nOSJYSQgbB_oSkbyW5L", text: "Stockholm", correct: !1 },
      { _key: "8U91yjAxnEYO2kgZwCzD6", text: "Helsinki", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "VtcrfQgshVnV1sMhIAN2s", text: "Kreta", correct: !0 },
      { _key: "ifjak30UrY4gCOoBp2DXh", text: "Mykonos", correct: !1 },
      { _key: "Xa2DC54wG49px3sWbElmY", text: "Naxos", correct: !1 },
    ],
    _key: "e1LOepD82YOiLEZvaa1ED",
    text: "Reis dit arkeologen Arthur Evans fant rester av en minoisk sivilisasjon",
    difficulty: "hard",
    category: null,
  },
  {
    _key: "LEYZXCw6aFaJfO_WmEDdq",
    text: "Sett deg i båten og ro til det sørligste punktet i Europa",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "1-gROv4ujwzoV0O9vosAY", text: "Gavdos", correct: !0 },
      { _key: "2Z2IDJzceQjLKoefO2zst", text: "Kypros", correct: !1 },
      { _key: "DLLWJP2Myls3J9fs_QtbD", text: "Milos", correct: !1 },
    ],
  },
  {
    _key: "9pxWDNPF9Eqdg1hUnMeIG",
    text: "Sumerisk er et utdødd språk som ble snakka av sumererne. Hvor levde de?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "dU_KWD0NPdNv8BWMRlR3j", text: "Mesopotamia", correct: !0 },
      { _key: "3QIsW1oEH8aP3ECj9DbP5", text: "Vinland", correct: !1 },
      { _key: "wg8835g-dDgEpyNZA3pu7", text: "Miklagard", correct: !1 },
    ],
  },
  {
    category: null,
    answers: [
      { _key: "GpuCBiKtGutzp5VRlg18g", text: "Svalbard", correct: !0 },
      { _key: "YDxvT0YIgxIoPIWJK6T8w", text: "Sibir", correct: !1 },
      { _key: "30l49n2qb4UiqkPWfbRmS", text: "Murmansk", correct: !1 },
    ],
    _key: "dJm8aePTGl0hbLJqO_uRz",
    text: "Hvor foregår handlinga i framtidsromanen «Drømmen om et tre» av Maja Lunde?",
    difficulty: "hard",
  },
  {
    _key: "A_-6w3zZv_59lybtn2VKK",
    text: "Slå følge med forfatter Maren Uthaug til stedet hun er født",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "QIawheJVt38t6puVrff59", text: "Kautokeino", correct: !0 },
      { _key: "3UCJST539iYP8cd18qIXp", text: "Haderslev", correct: !1 },
      { _key: "s1WCmA_Cd4ZwO2bx9_5fL", text: "Ørland", correct: !1 },
    ],
  },
  {
    answers: [
      { _key: "Gvl7eaE9PFqCyeVZ_kZQV", text: "Boknafjorden", correct: !0 },
      { _key: "k3N0Kz1q34-AAPKVNpZST", text: "Sognefjorden", correct: !1 },
      { _key: "DDRSELJGO1zXnDTwyoHI2", text: "Ranfjorden", correct: !1 },
    ],
    _key: "BPEuwUskgqdbIv1M8ah2M",
    text: "Hvilken fjord ligger øya Ombo i?",
    difficulty: "hard",
    category: null,
  },
  {
    _key: "8FvUcxUsh4W8fSfTEHENZ",
    text: "Hvor kan du gå den fryktede fjellveien Vårstigen?",
    difficulty: "hard",
    category: null,
    answers: [
      { _key: "mu8RoR9rXq-JeJuy6J_DB", text: "Oppdal", correct: !0 },
      { _key: "CRczxZ8yDl398JyGJBGsB", text: "Sel", correct: !1 },
      { _key: "kmyIsUSUv6KjGIMLW3Hkq", text: "Tydal", correct: !1 },
    ],
  },
];
